#!/bin/bash
echo "=== Final headers verification ==="
echo ""
echo "--- 1. _next/static JS chunk ---"
curl -sI http://98.93.252.250/_next/static/chunks/1255-ab54a41c275880be.js 2>&1 | grep -E "Cache-Control|Content-Type"
echo ""
echo "--- 2. Spine JSON with gzip ---"
curl -sI http://98.93.252.250/H501/idle_01/idle_1.json -H "Accept-Encoding: gzip" 2>&1 | grep -E "Cache-Control|Content-Encoding|Content-Type"
echo ""
echo "--- 3. Spine atlas with gzip ---"
curl -sI http://98.93.252.250/H501/idle_01/idle_1.atlas -H "Accept-Encoding: gzip" 2>&1 | grep -E "Cache-Control|Content-Encoding|Content-Type"
echo ""
echo "--- 4. bg PNG (11MB) ---"
curl -sI http://98.93.252.250/bg-stage1.png 2>&1 | grep -E "Cache-Control|Content-Type"
echo ""
echo "--- 5. Spine boss idle JSON ---"
curl -sI http://98.93.252.250/spine/assets/boss/idle_1.json -H "Accept-Encoding: gzip" 2>&1 | grep -E "Cache-Control|Content-Encoding|Content-Type"
echo ""
echo "--- 6. gzip_types in nginx.conf ---"
grep -n 'gzip_types' /etc/nginx/nginx.conf | grep -v "^#"
