CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY,
  total_damage_dealt BIGINT NOT NULL DEFAULT 0 CHECK (total_damage_dealt >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  email TEXT NOT NULL DEFAULT '',
  nickname TEXT NOT NULL DEFAULT '',
  avatar TEXT NOT NULL DEFAULT '👤'
);

CREATE TABLE IF NOT EXISTS public.user_inventory (
  user_id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  item_hand_count INTEGER NOT NULL DEFAULT 0 CHECK (item_hand_count >= 0),
  item_phallus_count INTEGER NOT NULL DEFAULT 0 CHECK (item_phallus_count >= 0),
  total_damage_dealt BIGINT NOT NULL DEFAULT 0 CHECK (total_damage_dealt >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.boss_status (
  boss_id UUID PRIMARY KEY DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  max_hp BIGINT NOT NULL DEFAULT 100000 CHECK (max_hp >= 0),
  current_hp BIGINT NOT NULL DEFAULT 100000 CHECK (current_hp >= 0),
  version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
  last_updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT boss_status_hp_limit CHECK (current_hp <= max_hp)
);

CREATE TABLE IF NOT EXISTS public.attack_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  item_used VARCHAR(20) NOT NULL CHECK (item_used IN ('item_hand', 'item_phallus')),
  damage_dealt BIGINT NOT NULL DEFAULT 0 CHECK (damage_dealt >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.user_daily_tasks (
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  daily_energy_consumed INT NOT NULL DEFAULT 0 CHECK (daily_energy_consumed >= 0),
  daily_money_recharged NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (daily_money_recharged >= 0),
  recharge_processed BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, date)
);

CREATE TABLE IF NOT EXISTS public.webhook_idempotency (
  tx_id TEXT PRIMARY KEY,
  processed_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.task_progress (
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  task_type VARCHAR(50) NOT NULL CHECK (task_type IN ('daily_energy', 'daily_recharge')),
  reset_date DATE NOT NULL DEFAULT CURRENT_DATE,
  current_progress INTEGER NOT NULL DEFAULT 0 CHECK (current_progress >= 0),
  is_claimed BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, task_type, reset_date)
);

CREATE TABLE IF NOT EXISTS public.milestone_rewards (
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  milestone_id INTEGER NOT NULL,
  is_claimed BOOLEAN NOT NULL DEFAULT false,
  claimed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  is_locked BOOLEAN NOT NULL DEFAULT false,
  reward_type TEXT NOT NULL DEFAULT 'MEDAL' CHECK (reward_type IN ('ENERGY', 'MEDAL')),
  reward_value TEXT NOT NULL DEFAULT '挑战勋章',
  PRIMARY KEY (user_id, milestone_id),
  CONSTRAINT milestone_rewards_locked_guard CHECK (
    NOT (is_locked = true AND is_claimed = true AND claimed_at IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS public.attack_idempotency (
  idempotency_key TEXT PRIMARY KEY,
  processed_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.activities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  type VARCHAR(10) NOT NULL CHECK (type IN ('LIVE2D', 'ENERGY')),
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  status VARCHAR(10) NOT NULL DEFAULT 'DISABLED' CHECK (status IN ('ENABLED', 'DISABLED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  config JSONB NOT NULL DEFAULT '{"isGlobalEnabled": false}'::jsonb,
  CONSTRAINT activities_end_after_start CHECK (end_time > start_time)
);

CREATE TABLE IF NOT EXISTS public.banners (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  image_url TEXT NOT NULL DEFAULT '',
  redirect_id TEXT NOT NULL DEFAULT '',
  redirect_type TEXT NOT NULL DEFAULT 'none' CHECK (redirect_type IN ('activity', 'external', 'none')),
  is_active BOOLEAN NOT NULL DEFAULT false,
  show_countdown BOOLEAN NOT NULL DEFAULT false,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.admin_audit_log (
  id BIGSERIAL PRIMARY KEY,
  route TEXT NOT NULL,
  action TEXT NOT NULL,
  operator_id TEXT NOT NULL,
  target_user_id TEXT NOT NULL,
  field_name TEXT,
  old_value TEXT,
  new_value TEXT,
  ip_address TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_user_inventory_updated_at ON public.user_inventory;
CREATE TRIGGER update_user_inventory_updated_at
BEFORE UPDATE ON public.user_inventory
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_user_daily_tasks_updated_at ON public.user_daily_tasks;
CREATE TRIGGER update_user_daily_tasks_updated_at
BEFORE UPDATE ON public.user_daily_tasks
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_task_progress_updated_at ON public.task_progress;
CREATE TRIGGER update_task_progress_updated_at
BEFORE UPDATE ON public.task_progress
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- ─── user_activity_stats ───────────────────────────────────────────────────
-- Per-(user, activity) accumulated damage. The source of truth for activity-
-- scoped milestone unlock thresholds and per-activity leaderboards.
-- One row per user per activity.
CREATE TABLE IF NOT EXISTS public.user_activity_stats (
  user_id      UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  activity_id  INTEGER NOT NULL REFERENCES public.activities(id) ON DELETE CASCADE,
  total_damage BIGINT NOT NULL DEFAULT 0 CHECK (total_damage >= 0),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, activity_id)
);

DROP TRIGGER IF EXISTS update_user_activity_stats_updated_at ON public.user_activity_stats;
CREATE TRIGGER update_user_activity_stats_updated_at
BEFORE UPDATE ON public.user_activity_stats
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();
